### ISSUE TITLE
Local-persist volume driver

### ISSUE THREAD

**Issue by woudsma** [barebaric/traefik-swarm#1]
Hi there. Thanks for sharing this repository!
I'm working on [Swarmlet](https://github.com/swarmlet/swarmlet) in which I'm trying to automate a basic swarm setup, a bit like setting up a server with [Dokku](https://github.com/dokku/dokku).
(It really is a learning project to get more familiar with Docker Swarm)
There's some tips in your README which I didn't consider, I'm going to look into those!

Did you consider other options to [MatchbookLab/local-persist](https://github.com/MatchbookLab/local-persist)?
The issue I'm currently trying to solve with Swarmlet is updating Traefik from v1.7 to v2+, so I need to find a way to securely store the Let's Encrypt SSL certs in a distributed way. Most of the local-persist code is 4+ years old, so I was wondering if you see issues there.

I've done -some- research, but it seems hard to find a good solution to store certificates in a Docker Swarm while using Traefik v2+. Except for this repo there aren't many solutions around. Which is a shame because I do like the simplicity of Traefik and Docker Swarm vs Kubernetes.

Not really an issue, so feel free to close this question.

edit: my first [docker-compose.yml](https://github.com/swarmlet/swarmlet/blob/feature/traefik-v2/modules/core/loadbalancer/docker-compose.yml) rewrite attempt (I can recommend using Docker Secrets to store passwords btw)

**Comment by knipknap** [comment]
I didn't really consider alternatives. If I were to move to a multi node setup that requires redundancy, I would probably go with GlusterFS; we have been using that in production sucessfully (though on Kubernetes). Otherwise I would put a constraint on containers requiring persistance, to place them on a single node.

I didn't encounter any issues with local-persist, it seems to be working robustly so far.
